-- O primeiro administrador deve ser provisionado por ambiente.
--
-- Execute manualmente no SQL Editor do projeto, substituindo o endereço:
--
-- insert into private.admin_allowlist (email)
-- values (lower('admin@exemplo.com'))
-- on conflict (email) do nothing;
--
-- Se o usuário já existir, promova-o deliberadamente após conferir a identidade.
-- Identificadores pessoais não devem ser gravados em migrations versionadas.
select 1;
